### PR TITLE
set inital proposalDeposit = 0 ether

### PR DESCRIPTION
**Pull request by colm**
solves 
https://github.com/slockit/DAO/issues/60

### CODE REVIEW

**Comment by CJentzsch** [comment]
The initial value doesn't matter much, as long as it is non-zero to provide spam.
The DAO can change this value at any time, by making a proposal to call this function: https://github.com/slockit/DAO/blob/master/DAO.sol#L676

**Comment by colm** [comment]
But in order to pass that proposal someone has to put forward 20 ETH deposit. Correct?

Imagine a future where 1 ETH is 1,000 USD. Someone tries to split the DAO and withdraw their ETH. The new DAO has an initial proposal deposit of 20ETH tehy don't have 20,000 USD  so they cannot make a proposal to change the proposal deposit.

**Comment by LefterisJP** [comment]
As per our discussion in the slack I believe that issue can be up for discussion.
The code here is for a "generic" DAO which will act as a template for all others.
As mentioned in the chat, when splitting it can be a real problem if the person has not enough ether to make a proposal.

I can see 2 solutions here:

1) **Short-term**: Change it to much lower value, but not zero so as to still (kind of) discourage spam. Say 0.01 ETH. The _serious_ DAOs can then make proposals to change their deposit values to more appropriate levels to totally stop spam.

2) **Long-term** Have more special types of proposals. For example detect if the DAO just split out and then make the first proposal deposit-free. Or even make the proposal-deposit change proposals free of deposit. There are a lot of possible options here, but the gist of it is, to have adjustable deposit depending on proposal type.

**Comment by LefterisJP** [comment]
Or even a more elegant short term solution would be:

3) make the proposal deposit a constructor argument so that the initial DAO deployer decides on it. Plus give a default value of `0` when creating a DAO from a `DAOCreator` during a spit so that split DAOs have no artificial caps that make assumptions about ether market value.

**Comment by colm** [comment]
I like no 3. Seems to be best of both worlds with very little added complexity.

**Pull request closed without merging**
