### PR TITLE
Add Chinese translation version white paper

### PR DESCRIPTION
**Pull request by u2**
I have translated the white paper into Chinese.But it's not the latest version.There were many changes of the white paper during the translating, I did not follow up in time.

### CODE REVIEW

**Comment by CJentzsch** [comment]
Let me know when you think it is ready to be merged.

**Comment by u2** [comment]
I am glad to update up-to-date, but I am a little busy these days.
If you don't mind,it's better to merge it, then I will write a post for asking anyone who like to contribute for it.

**Comment by u2** [comment]
Bump

**Comment by CJentzsch** [comment]
I have to remark, I don't speak chinese so I trust you ...  :-)

**Pull request merged**
