### PR TITLE
add updateClientAddress function

### PR DESCRIPTION
**Pull request by CJentzsch**
in the case the DAO updates it contract, it should also be able to update its address here

### CODE REVIEW

**Comment by LefterisJP** [comment]
Hmm but then this call should be timed very correctly by the DAO's users so that it happens right before a proposal to move to a new contract is passed.

So the process would be like that:

1) Deploy a new DAO contract. Get its address
2) Make  a proposal to call `updateClientAddress(addressOfDAODeployatAtStep1)` function. Once this proposal passes then no further interaction with the contractor is possible.
3) Make a proposal (and pass it) to call `newContract(addressOfDAODeployatAtStep1)`

From step 2 and on all proposals *have to* pass. That's kinda dangerous.

**Comment by CJentzsch** [comment]
No, they can safely do this after they update there contract with `newContract` .
This function "only" moves all the ether and rewardTokens. But they cans till make a proposal an vote for that in order to call `updateClientAddress`.

**Comment by CJentzsch** [comment]
@LefterisJP please explain in the case you still think there is a problem

**Comment by LefterisJP** [comment]
@CJentzsch No I don't believe there is a problem. Still they would have to manage to get a quorum in a vote in the old DAO to change the contractor. I guess at least with the current model there is no way to avoid this.

**Comment by CJentzsch** [comment]
yes. But even if they don't, it wouldn't be a big problem. The rewards would still get forwarded.

**Pull request merged**
